name: Est
main: cf.melncat.est.Est
version: 1.0.0
depend:
  - ProtocolLib
  - NBTAPI
  - ItemBridge
  - Vault
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.6.10
  - org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.10
  - org.jetbrains.kotlin:kotlin-reflect:1.6.10
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2
  - org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.0
  - org.tukaani:xz:1.9

api-version: 1.18